/**
 * fragment-store.ts — Fragmented Linked-Graph Architecture
 *
 * Splits a monolithic graph into small "island" fragments with shared
 * "bridge" nodes. The MCP server loads only the fragments it needs
 * and stitches them in memory via reference ID pointers.
 *
 * Directory layout:
 *   .swiftprism/
 *     graph-index.json              — lightweight { nodeId → file } lookup
 *     fragments/
 *       _shared.json                — nodes referenced by 2+ buckets (bridges)
 *       _targets.json               — target hubs + entry points
 *       _globals.json               — top-level functions without a parent object
 *       AppDelegate.json            — Object + its members
 *       HomeViewModel.json          — Object + its members
 *       ...
 *
 * Reference pointers:
 *   Inside AppDelegate.json, a call to "MyApp::HomeViewModel::fetch()"
 *   is just a string ID. The server resolves it via the index to find
 *   which fragment file contains that node, loads only that file, and
 *   merges the result.
 */

import * as fs from "fs";
import * as path from "path";

// ═══════════════════════════════════════════════════════════════════════════════
// TYPES
// ═══════════════════════════════════════════════════════════════════════════════

export interface GraphNode {
  id: string;
  name: string;
  flavor: string;
  location: { absPath: string; line: number; col: number };
  parents: string[];
  calls?: string[];
  returns?: string[];
  parameters?: string[];
  inits?: string[];
  deinits?: string[];
  extends?: string | null;
  implements?: string[];
  stores?: string[];
  locations?: { absPath: string; line: number; col: number }[];
  origin?: string;
  /** Token-optimized context generated by local LLM or deterministic fallback */
  node_context?: string;
}

export interface GraphIndex {
  version: string;
  generatedAt: string;
  nodeCount: number;
  fragmentCount: number;
  sharedCount: number;
  /** nodeId → fragment filename (no directory prefix) */
  map: Record<string, string>;
}

const OBJECT_FLAVORS = new Set(["struct", "class", "enum", "actor", "protocol"]);
const TARGETS_FILE = "_targets.json";
const SHARED_FILE = "_shared.json";
const GLOBALS_FILE = "_globals.json";
const INDEX_FILE = "graph-index.json";

// ═══════════════════════════════════════════════════════════════════════════════
// FRAGMENTER — "Rã nhỏ" engine with shared-node detection
// ═══════════════════════════════════════════════════════════════════════════════

export function flattenGraph(parsed: unknown): GraphNode[] {
  if (Array.isArray(parsed)) return parsed as GraphNode[];
  const doc = parsed as { node?: Nested; nodes?: Nested[] };
  const root = doc.node?.nodes ? doc.node : doc.nodes?.length === 1 && doc.nodes[0]?.nodes ? doc.nodes[0] : null;
  if (!root) return (doc.nodes as GraphNode[] | undefined) ?? [];
  const out: GraphNode[] = [];
  const walk = (node: Nested, chain: string[]) => {
    const calls = (node.calls ?? []).map((c) => (typeof c === "string" ? c : c.target));
    const isLeaf = node.kind === "leaf" || ((node.nodes ?? []).length === 0 && node.kind !== "project" && node.kind !== "archipelago");
    if (isLeaf) {
      out.push({
        id: node.id,
        name: node.name,
        flavor: node.flavor || "symbol",
        location: {
          absPath: node.location?.absPath ?? "",
          line: node.location?.line ?? 1,
          col: 1,
        },
        parents: chain,
        calls,
      });
    }
    const next = isLeaf ? chain : [...chain, node.name];
    for (const child of node.nodes ?? []) walk(child, next);
  };
  for (const child of root.nodes ?? []) walk(child, []);
  return out;
}

interface Nested {
  id: string;
  name: string;
  kind?: string;
  flavor?: string;
  location?: { absPath?: string; line?: number };
  calls?: Array<string | { target: string }>;
  nodes?: Nested[];
}

export function fragmentGraph(graphPath: string, outputDir: string): GraphIndex {
  const raw = fs.readFileSync(graphPath, "utf-8");
  const parsed = JSON.parse(raw);
  const nodes: GraphNode[] = flattenGraph(parsed);

  const fragmentsDir = path.join(outputDir, "fragments");
  // Clean old fragments before writing
  if (fs.existsSync(fragmentsDir)) {
    for (const f of fs.readdirSync(fragmentsDir)) {
      if (f.endsWith(".json")) fs.unlinkSync(path.join(fragmentsDir, f));
    }
  }
  fs.mkdirSync(fragmentsDir, { recursive: true });

  const nodeById = new Map(nodes.map((n) => [n.id, n]));

  // ── Step 1: Assign each node to a bucket ──
  // Bucket key = top-level object ID (Target::ObjectName) or special keys
  const bucketOf = new Map<string, string>(); // nodeId → bucketKey

  for (const node of nodes) {
    if (node.flavor === "target" || node.flavor === "entry_point") {
      bucketOf.set(node.id, TARGETS_FILE);
      continue;
    }

    if (OBJECT_FLAVORS.has(node.flavor)) {
      bucketOf.set(node.id, node.id); // Object is its own bucket
      continue;
    }

    // Members: find top-level object parent
    const objParent = node.parents.find((p) => p.includes("::"));
    if (objParent) {
      const segs = objParent.split("::");
      const topObj = segs.length >= 2 ? `${segs[0]}::${segs[1]}` : objParent;
      bucketOf.set(node.id, topObj);
    } else {
      bucketOf.set(node.id, GLOBALS_FILE);
    }
  }

  // ── Step 2: Count cross-bucket references to detect shared nodes ──
  // A node referenced (called/stored/init'd) by nodes in 2+ different buckets → shared
  const referencedByBuckets = new Map<string, Set<string>>(); // nodeId → Set<bucketKey>

  for (const node of nodes) {
    const sourceBucket = bucketOf.get(node.id) ?? GLOBALS_FILE;
    const refs = [
      ...(node.calls ?? []),
      ...(node.inits ?? []),
      ...(node.stores ?? []),
    ];
    for (const ref of refs) {
      if (!nodeById.has(ref)) continue; // external reference, skip
      const entry = referencedByBuckets.get(ref) ?? new Set();
      entry.add(sourceBucket);
      referencedByBuckets.set(ref, entry);
    }
  }

  // Promote multi-referenced nodes to shared bucket
  for (const [nodeId, buckets] of referencedByBuckets) {
    if (buckets.size >= 2) {
      const current = bucketOf.get(nodeId);
      // Don't promote targets (already in their own file) or the node's own bucket members
      if (current && current !== TARGETS_FILE) {
        bucketOf.set(nodeId, SHARED_FILE);
      }
    }
  }

  // ── Step 3: Group nodes by final bucket and write fragments ──
  const buckets = new Map<string, GraphNode[]>();
  for (const node of nodes) {
    const key = bucketOf.get(node.id) ?? GLOBALS_FILE;
    const arr = buckets.get(key) ?? [];
    arr.push(node);
    buckets.set(key, arr);
  }

  const indexMap: Record<string, string> = {};
  let fragmentCount = 0;

  // Map bucket keys to filenames
  function bucketToFile(key: string): string {
    if (key === TARGETS_FILE || key === SHARED_FILE || key === GLOBALS_FILE) return key;
    // Target::ClassName → ClassName.json
    const segs = key.split("::");
    const safe = segs[segs.length - 1].replace(/[^a-zA-Z0-9_()-]/g, "_");
    return `${safe}.json`;
  }

  // Handle filename collisions (two objects with same class name in different targets)
  const usedFiles = new Set<string>();

  for (const [key, bucketNodes] of buckets) {
    let fileName = bucketToFile(key);
    if (usedFiles.has(fileName) && fileName !== TARGETS_FILE && fileName !== SHARED_FILE && fileName !== GLOBALS_FILE) {
      // Collision: prefix with target name
      const segs = key.split("::");
      fileName = segs.length >= 2 ? `${segs[0]}_${segs[1]}.json` : `_dup_${fileName}`;
    }
    usedFiles.add(fileName);

    fs.writeFileSync(path.join(fragmentsDir, fileName), JSON.stringify(bucketNodes));
    for (const node of bucketNodes) {
      indexMap[node.id] = fileName;
    }
    fragmentCount++;
  }

  const sharedCount = (buckets.get(SHARED_FILE) ?? []).length;

  const index: GraphIndex = {
    version: "2.0",
    generatedAt: new Date().toISOString(),
    nodeCount: nodes.length,
    fragmentCount,
    sharedCount,
    map: indexMap,
  };
  fs.writeFileSync(path.join(outputDir, INDEX_FILE), JSON.stringify(index));

  return index;
}

// ═══════════════════════════════════════════════════════════════════════════════
// FRAGMENT LOADER — Load-on-demand with reference stitching
//
// The loader NEVER holds the full graph. It reads fragment files on request,
// resolves reference IDs across fragments, and returns the merged subgraph.
// After the caller processes the result, all node data is GC'd.
// ═══════════════════════════════════════════════════════════════════════════════

export class FragmentLoader {
  private readonly indexPath: string;
  private readonly fragmentsDir: string;
  private index: GraphIndex | null = null;

  constructor(stealthDir: string) {
    this.indexPath = path.join(stealthDir, INDEX_FILE);
    this.fragmentsDir = path.join(stealthDir, "fragments");
  }

  get available(): boolean {
    return fs.existsSync(this.indexPath);
  }

  // ── Index management ──

  private ensureIndex(): GraphIndex | null {
    if (this.index) return this.index;
    if (!fs.existsSync(this.indexPath)) return null;
    try {
      this.index = JSON.parse(fs.readFileSync(this.indexPath, "utf-8"));
      return this.index;
    } catch {
      return null;
    }
  }

  invalidate(): void {
    this.index = null;
  }

  getStats(): { nodeCount: number; fragmentCount: number; sharedCount: number; generatedAt: string } | null {
    const idx = this.ensureIndex();
    if (!idx) return null;
    return { nodeCount: idx.nodeCount, fragmentCount: idx.fragmentCount, sharedCount: idx.sharedCount, generatedAt: idx.generatedAt };
  }

  getAllNodeIds(): string[] {
    const idx = this.ensureIndex();
    return idx ? Object.keys(idx.map) : [];
  }

  // ── Single fragment I/O ──

  private loadFragment(fileName: string): GraphNode[] {
    const filePath = path.join(this.fragmentsDir, fileName);
    if (!fs.existsSync(filePath)) return [];
    try {
      return JSON.parse(fs.readFileSync(filePath, "utf-8"));
    } catch {
      return [];
    }
  }

  resolveFragment(nodeId: string): string | null {
    const idx = this.ensureIndex();
    return idx?.map[nodeId] ?? null;
  }

  // ── Node loading ──

  loadNode(nodeId: string): GraphNode | null {
    const file = this.resolveFragment(nodeId);
    if (!file) return null;
    const nodes = this.loadFragment(file);
    return nodes.find((n) => n.id === nodeId) ?? null;
  }

  /** Load multiple nodes, grouping by fragment file to minimize reads */
  loadNodes(nodeIds: string[]): GraphNode[] {
    const idx = this.ensureIndex();
    if (!idx) return [];

    const byFragment = new Map<string, Set<string>>();
    for (const id of nodeIds) {
      const file = idx.map[id];
      if (!file) continue;
      const group = byFragment.get(file) ?? new Set();
      group.add(id);
      byFragment.set(file, group);
    }

    const result: GraphNode[] = [];
    for (const [file, idSet] of byFragment) {
      for (const node of this.loadFragment(file)) {
        if (idSet.has(node.id)) result.push(node);
      }
    }
    return result;
  }

  loadShared(): GraphNode[] {
    return this.loadFragment(SHARED_FILE);
  }

  loadTargets(): GraphNode[] {
    return this.loadFragment(TARGETS_FILE);
  }

  loadObject(objectId: string): GraphNode[] {
    const file = this.resolveFragment(objectId);
    if (!file) return [];
    return this.loadFragment(file);
  }

  // ── Stitching: load a subgraph by resolving all reference pointers ──

  /**
   * Given a set of seed node IDs, load them plus all nodes they reference
   * (calls, inits, stores) up to `depth` levels. Automatically loads
   * shared globals. Returns the merged subgraph — nothing persists.
   */
  stitch(seedIds: string[], depth: number = 2): { nodes: GraphNode[]; missing: string[] } {
    const collected = new Map<string, GraphNode>();
    const missing: string[] = [];
    let frontier = new Set(seedIds);

    for (let d = 0; d <= depth; d++) {
      if (frontier.size === 0) break;

      const needed = [...frontier].filter((id) => !collected.has(id));
      if (needed.length === 0) break;

      const loaded = this.loadNodes(needed);
      const loadedIds = new Set(loaded.map((n) => n.id));

      for (const node of loaded) {
        collected.set(node.id, node);
      }

      // Track missing references
      for (const id of needed) {
        if (!loadedIds.has(id)) missing.push(id);
      }

      // Next frontier: all references from the nodes we just loaded
      const nextFrontier = new Set<string>();
      if (d < depth) {
        for (const node of loaded) {
          for (const ref of [...(node.calls ?? []), ...(node.inits ?? []), ...(node.stores ?? [])]) {
            if (!collected.has(ref)) nextFrontier.add(ref);
          }
          // Also load parents to provide structural context
          for (const p of node.parents) {
            if (p.includes("::") && !collected.has(p)) nextFrontier.add(p);
          }
        }
      }
      frontier = nextFrontier;
    }

    // Always include shared globals (targets) — they're small
    for (const shared of this.loadTargets()) {
      if (!collected.has(shared.id)) collected.set(shared.id, shared);
    }

    return { nodes: Array.from(collected.values()), missing };
  }

  // ── Streaming scan (for search) ──

  forEachFragment(callback: (nodes: GraphNode[], fileName: string) => void): void {
    if (!fs.existsSync(this.fragmentsDir)) return;
    for (const file of fs.readdirSync(this.fragmentsDir)) {
      if (!file.endsWith(".json")) continue;
      const nodes = this.loadFragment(file);
      callback(nodes, file);
    }
  }
}
